services:
  - name: PRIOD
    type: web
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: priod
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
    plan: free
    region: oregon
    autoDeploy: true
