services:
  - name: PRIOD
    type: web
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-cuke8r3tq21c73e62nug-a
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: dbpriod
      - key: DB_USERNAME
        value: dbpriod_user
      - key: DB_PASSWORD
        sync: false
    plan: free
    region: oregon
    autoDeploy: true
